### ISSUE TITLE
Python 3.11 install fails

### ISSUE THREAD

**Issue by gbouras13** [linsalrob/spae#2]
I'm trying to install spae in a conda env with Python 3.11 installed.

Seems like Snakemake has an issue with Python 3.11 and ratelimiter.

https://stackoverflow.com/questions/74343982/module-asyncio-has-no-attribute-coroutine-on-snakemake

phage_genome_assembly install database --snake-default="--conda-frontend conda"

Config file /hpcfs/users/a1667917/spae/phage_genome_assembly/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /hpcfs/users/a1667917/spae/phage_genome_assembly/workflow/../config/databases.yaml is extended by additional config specified via the command line.
Databases are being saved in, databases 

Building DAG of jobs...
Traceback (most recent call last):
  File "/hpcfs/users/a1667917/myconda/envs/spae/lib/python3.11/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/hpcfs/users/a1667917/myconda/envs/spae/lib/python3.11/site-packages/snakemake/workflow.py", line 943, in execute
    self.scheduler = JobScheduler(
                     ^^^^^^^^^^^^^
  File "/hpcfs/users/a1667917/myconda/envs/spae/lib/python3.11/site-packages/snakemake/scheduler.py", line 105, in __init__
    from ratelimiter import RateLimiter
  File "/hpcfs/users/a1667917/myconda/envs/spae/lib/python3.11/site-packages/ratelimiter.py", line 36, in <module>
    class RateLimiter(object):
  File "/hpcfs/users/a1667917/myconda/envs/spae/lib/python3.11/site-packages/ratelimiter.py", line 127, in RateLimiter
    __aexit__ = asyncio.coroutine(__exit__)
                ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

Installation in a python 3.10 env works fine.

Separately, I ran into this issue with snakemake https://github.com/snakemake/snakemake/issues/1899 

with Snakemake 7.14.0. I changed setup.py to be snakemake>=7.14.0 and it works fine for me now with snakemake 7.19.1.

This will be in the pull request when I am done adding the Medaka module.

George

**Comment by npbhavya** [comment]
Should be resolved now.
